export { Header } from './Header'
export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as Stats } from './Stats'
export { default as CallToAction } from './CallToAction'
export { default as Footer } from './Footer'
