name = "beekeeper"
compatibility_date = "2024-06-06"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm dlx @cloudflare/next-on-pages"
pages_build_output_dir = ".vercel/output/static"

[site]
bucket = ".vercel/output/static"

[build.upload]
format = "service-worker"

[env.production]
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[env.preview]
compatibility_flags = ["nodejs_compat"]
workers_dev = true
